### ISSUE TITLE
La lanza se puede lanzar incluso aturdido por el pteranodon.

### ISSUE THREAD

**Issue by ARodulfo** [Proyectos1-FDI-UCM/c2021-Grupo01#10]
% La lanza se puede lanzar incluso aturdido por el pteranodon.
% Alfonso Jaime Rodulfo Guío 
% 27/05/2021

### Descripción

He podido lanzar la lanza incluso estando aturdido por el pteranodon.
Entiendo que no es una decisión de diseño, y no se debería poder lanzar la lanza
aturdido.

### Pasos 

1. Ponerte a rango de aturdida del pteranodon.
2. Esperar a que te aturda el pteranodon.
3. Mientras estés aturdido, lanzar la lanza.

### Captura de pantalla o vídeo

https://youtu.be/uVv-2Xba304

**Comment by Bimbloc** [comment]
Ciertamente, no deberias poder lanzarla.
gracias!
