### ISSUE TITLE
La lanza se destruye al lanzarla junto a una pared vertical

### ISSUE THREAD

**Issue by dcasiano** [Proyectos1-FDI-UCM/c2021-Grupo01#6]
David Casiano Flores
26/05/2021

**La lanza se destruye al lanzarla junto a una pared vertical**

Descripción

Al situar al jugador al lado de una pared vertical (por ejemplo la de los extremos izquierdo y derecho del mapa), si se realiza el ataque de la lanza, esta es destruida justo cuando aparece.

Pasos

1. Situarse pegado a una pared vertical
2. Realizar el ataque de la lanza

**Comment by Sebana02** [comment]
El collider de la lanza era demasiado grande y chocaba con los colliders del tilemap al salir. Se le ha reducido el collider a la lanza.
