### ISSUE TITLE
No te caes por el precipicio si llegas a él desde un dash

### ISSUE THREAD

**Issue by PabloEtayo** [Proyectos1-FDI-UCM/c2021-Grupo01#7]
**Descripción**

Si intentas pasar sobre un precipicio con un dash pero un obstáculo te impide llegar al otro lado y te quedas sobre el precipicio, no te mueres.

**Pasos**

 1. Situarse en el recinto del enemigo guerrero (el que no es dinosaurio)
 2. Colocarse frente al precipicio dejando la roca que hay al otro lado frente al jugador
 3. Pulsar espacio para hacer el dash

![Captura1](https://user-images.githubusercontent.com/62880904/119738807-954f6880-be81-11eb-9e04-13bf7641552b.png)
![Captura2](https://user-images.githubusercontent.com/62880904/119738814-97b1c280-be81-11eb-9ed1-1210b1242639.png)

**Comment by Sebana02** [comment]
Acorde al diseño del videojuego, al realizar un dash puedes atravesar un precipicio sin caerte. En este caso en especifico, al estar implementado el precipicio con un trigger enter, si te chocabas con otro collider y te quedabas dentro del trigger del precipicio no te morías. No obstante, en la versión final no se da ningún caso parecido a este, por tanto, se da por solucionado el error.
