### ISSUE TITLE
Los enemigos no se mueren si estás junto a ellos

### ISSUE THREAD

**Issue by PabloEtayo** [Proyectos1-FDI-UCM/c2021-Grupo01#8]
**Descripción**

Si te quedas quieto junto a un enemigo (que no sea el pteranodon), tras atacarte una vez dejará de hacerlo y no podrás matarle.

**Pasos**

 1. Sitúate junto a un enemigo cualquiera que no sea el pteranodon y deja que te ataque
 2. Espera y observa que no te ataca
 3. Atácale con el ataque de T-Rex o de anquilosaurio más de tres veces y verás que no muere

![Captura3](https://user-images.githubusercontent.com/62880904/119741242-97b3c180-be85-11eb-9cd4-81493b041a94.png)

**Comment by nahigles** [comment]
Arreglado gracias al knockback que se añadió a todos los enemigos. Con el knockbak el jugador es impulsado hacia atrás y los enemigos vuelven a atacar y pueden morirse si el jugador los ataca.
